// Updated layout.js with additional modern fonts
import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Outfit, Plus_Jakarta_Sans, Space_Grotesk, Lexend } from "next/font/google";
import "./globals.css";

import Footer from '../components/Footer'
import Nav from '../components/Nav'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Additional modern font options
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${outfit.variable} ${jakarta.variable} ${spaceGrotesk.variable} ${lexend.variable} antialiased`}
      >
      <Nav />
        {children}
      <Footer />
      </body>
    </html>
  );
}